### ISSUE TITLE
Document test setup and execution 

### ISSUE THREAD

**Issue by aidylewis** [bbc/gatling-load-tests#15]
.. for other members of the load-test-team. 

Include: 
* Set-up
* Certs
* Docker?
* Media Selector tests

**Comment by PoornimaGunisetti** [comment]
Also please include steps/configurations to run Gatling tests from Reith and Off-Reith.

**Comment by adrianlewis** [comment]
I have decided to use docker.

**Comment by aidylewis** [comment]
You can run the Gatling tests through Reith by adding a proxy in the [http protocol](http://gatling.io/docs/2.1.4/http/http_protocol.html#proxy-parameters). All configuration is now automatic with the 'cf' command.
