### ISSUE TITLE
How are we best to trigger?

### ISSUE THREAD

**Issue by mikechapman101** [bbc/gatling-load-tests#19]
We need to think about how we should trigger these performance tests, via cron? Always running on a cycle? Via Jenkins? On check-in? Every check-in? Selected release candidates?

Whatever we chose it cannot be a manual execution else it defeats the point, so we may need to experiment with a few methods to see which works best

**Comment by aidylewis** [comment]
I think a cron job within jenkins on a nightly basis. I'll set up a jenkins server next week.

**Comment by aidylewis** [comment]
I now think we should run a load test after each check-in as part of a CD pipeline. This is just a matter of setting a Jenkins option box. In reality however, developers would want to trigger their load tests after a passing acceptance test run.
