### ISSUE TITLE
How do you compare results?

### ISSUE THREAD

**Issue by mikechapman101** [bbc/gatling-load-tests#20]
In an ideal world I'd like every check-in/selected release candidate to be able to indicate whether the performance of the page/code has increased or decreased and by how much.

Obviously loadtesting is an aggregation of results over the period of the test and is generally not a single measurement that can be easily compared better/worse.

So how do we determine if performance is increasing or decreasing in order to be able to ties this to some sort of threshold that either flags a warning... or even stops the build progressing any further

**Comment by aidylewis** [comment]
We can query influxdb through the grafana query editor or curl the database with attached sql queries and present the results back to jenkins. 
http://docs.grafana.org/datasources/influxdb/#influxdb-query-editor
http://influxdb.com/docs/v0.8/api/reading_and_writing_data.html#querying-through-the-http-api

**Comment by aidylewis** [comment]
The Gatling Jenkins plugin provides performance trends across builds.
