### ISSUE TITLE
Continuous Perf Testing - Other tools

### ISSUE THREAD

**Issue by mikechapman101** [bbc/gatling-load-tests#22]
I realise this is not necessarily within the scope of this space (as it's the galting-load-tests space), but once we have our Continuous Perf Testing model in place and working I'd like us to try doing the same with other tools as I think this will help widen our knowledge and improve our understanding of the different challenges faced on the road to perf automation.

This is a lower priority requirement than the others at present

**Comment by PoornimaGunisetti** [comment]
Raised it in SOASTA Idea Exchange community : http://cloudlink.soasta.com/t5/SOASTA-Idea-Exchange/Does-CloudTest-support-Graphite/idi-p/40961

**Comment by aidylewis** [comment]
If they gave us a REST API where we could query the real-time stats, I could then write some code that formats the data and pushes it to the Graphite protocol.

**Comment by aidylewis** [comment]
How is this going?

**Comment by aidylewis** [comment]
SOASTA will be coming in to advise on this!
