### ISSUE TITLE
Append Errors graph with Passed vs Failed

### ISSUE THREAD

**Issue by PoornimaGunisetti** [bbc/gatling-load-tests#48]
Can we amend Errors graph to include passed transactions too. So rather than having only failed transactions (KO count), we can include passed transactions (OK count) too and edit graph title from "Errors" to "Passed vs Failed".

![screen shot 2015-06-30 at 11 55 59](https://cloud.githubusercontent.com/assets/8298062/8429426/7018749c-1f1f-11e5-822e-280b1ad5038f.png)

**Comment by aidylewis** [comment]
fixed
